### ISSUE TITLE
Where and how can I edit the bot?

### ISSUE THREAD

**Issue by FreshImmuc** [vured/vured-bot#36]
What file is the bot or in what directory is it?

**Comment by ckocyigit** [comment]
Not to interfere with this question, but this seems a bit to non-descriptive.

What do you mean with"What file is the bot"?

All of the code within the repository is the bot :)

**Comment by jonaznas** [comment]
You can find the main function to run the bot in [Vured.kt](https://github.com/vured/vured-bot/blob/main/src/main/kotlin/dev/jonaz/vured/bot/Vured.kt) and the services are started in [Application.kt](https://github.com/vured/vured-bot/blob/main/src/main/kotlin/dev/jonaz/vured/bot/application/Application.kt) 😊
