### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by FreshImmuc** [vured/vured-bot#37]
Hey, I'm trying to install the bot, but I just don't really know Java and stuff.

1. how do i install / build it?
2. where do I have to do which command? In the description there is only one command for docker.

Know me with the stuff relatively well just not with the build process and the structure of Java projects.

**Comment by jonaznas** [comment]
Hey 👋,

if you just want to use the bot you can deploy it to Heroku by clicking the "Deploy to Heroku" button.
You will be asked to enter some data, that's it. The free tier from Heroku is enough to run it.
If you have a server with docker installed (or you've installed it on your own system) you just have to enter 

> docker run -d --name vured-bot -e BOT__TOKEN="" -e DISCORD__GUILD=0 -e DISCORD__MUSIC_CHANNEL=0 -e DISCORD__ACCESS_ROLE=0 jonaznas/vured-bot:latest

(replace the ids before running the command).

To build the project download the repository, extract it and run `./gradlew.bat build` (windows). The compiled files are generated in `build/libs`.

**Comment by FreshImmuc** [comment]
okay, and how do I start it then after the build finished?

**Comment by jonaznas** [comment]
Go into the build folder where the files are generated and type `java -jar -Denv=prod vured-bot-(version).jar` in your terminal.
To get the bot working you need to set this environment variables in your system or environment

Variable | Description
------------- | -------------
BOT__MAX_PLAYLIST_TRACKS | The maximum Tracks that can be in the queue
BOT__TOKEN  | The discord bot token
DISCORD__ACCESS_ROLE | Role ID that can access the bot
DISCORD__GUILD | Discord Guild ID
DISCORD__LOG_CHANNEL | Text-Channel ID for logs
DISCORD__MUSIC_CHANNEL | Text-Channel ID for static message

**Comment by FreshImmuc** [comment]
environment variables are with an .env file right? if yes, in what folder?

**Comment by jonaznas** [comment]
If you compile it yourself you can also change it in `src/main/resources/application-prod.conf` but the bot token must be set as an environment variable. Here is a guide for it on windows: [Create and Modify Environment Variables on Windows](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html)

**Comment by FreshImmuc** [comment]
hmm okay I can try that.. but please add complete installation or/and build instructions in the Readme or WiKi for the bot.

**Comment by jonaznas** [comment]
I plan to improve the docs in near future :)
