### ISSUE TITLE
Help configuring HTTPS in docker on a VM

### ISSUE THREAD

**Issue by rehmedy** [vured/vured-bot#41]
I recently installed vured-bot onto a VM I own by using docker, and I was able to get the bot working on my server. However, while I can access the web server via http by using {ip address}:8080 (which gives me a successful redirect to the Github wiki page), attempting to access the web server with **https://**{ip address}:8080 gives me the following error: Secure Connection Failed - An error occurred during a connection to {ip address}:8080. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG.

I'm trying to access the web server via HTTPS so I can connect it to the web ui, but I've only had success accessing it via HTTP. I believe the error I am getting means that I need to setup SSL certificates to allow HTTPS connections to the web server, but I am not sure how to do this since I can't find an apache or nginx web server to attach SSL certificates to. However, maybe I am totally off base, so I am welcome to any suggestions!

**Comment by jonaznas** [comment]
Hey 👋

the easiest way is to add your domain to cloudflare and enable the cloud. Then you'll have a SSL connection without the need of an own certificate.

**Comment by rehmedy** [comment]
Thank you! That worked perfectly, just had to add a -p 80:8080 flag to the docker command to route it through normal http and that portion works flawlessly now.
